### ISSUE TITLE
Reproduce bug of missing transactions with QA

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-client-gateway#1124] opened 2024-02-12 07:02 UTC
See thread for further information
https://5afe.slack.com/archives/C05HTQ67JAJ/p1707310835777929

May be related to the errors in the events-service, we need to check it: https://5afe.slack.com/archives/C053WU61S95/p1707914326845199

**Comment by liliya-soroka** [comment] 2024-07-04 09:10
can not reproduce now

**Comment by iamacook** [comment] 2024-07-04 09:27
> can not reproduce now

I'd suggest we close this now then (if you are in agreement). Consuming the queue directly likely solved this issue.

**Comment by hectorgomezv** [comment] 2024-07-04 10:09
Yes, I'm under the same impression, it seems since we are consuming the events from the Transaction Service instead of relying on the Events Service solved this.

**Closed** 2024-08-21 17:22 UTC
Labels: bug
